version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - '5432:5432'
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    links:
      - "db:db"
    ports:
      - "8090:8080"